name: Setup Node and PNPM
description: Installs Node, PNPM and dependencies

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 24.14.0
        cache: "pnpm"
    - shell: bash
      run: pnpm install
