name: Setup Node and PNPM
description: Installs Node, PNPM and dependencies

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 22.19.0
        cache: "pnpm"
    - shell: bash
      run: pnpm install
