name: Setup Node and PNPM
description: Installs Node, PNPM and dependencies

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version: 22
        cache: "pnpm"
    - shell: bash
      run: pnpm install
