name: Setup Node and PNPM
description: Installs Node, PNPM and dependencies

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: 22
        cache: "pnpm"
    - shell: bash
      run: pnpm install
