name: Setup Node and PNPM
description: Installs Node, PNPM and dependencies

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24.10.0
        cache: "pnpm"
    - shell: bash
      run: pnpm install
