apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging
  template:
    metadata:
      labels:
        app: staging
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: staging
          image: registry.aarnihalinen.fi/homepage:next
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      securityContext: {}
