version: "3.7"

# https://playwright.dev/docs/docker
services:
  e2e:
    build:
      context: ..
      dockerfile: tests/Dockerfile
    image: e2e-tests:latest
    ipc: host # Using --ipc=host is recommended when using Chrome (Docker docs). Chrome can run out of memory without this flag.
    volumes:
      - ./tests:/test-runner/tests:rw
      # Volumes for results
      - ./playwright-report:/test-runner/playwright-report:rw
      - ../test-results:/test-runner/test-results:rw
    command: ["pnpm", "test", "--", "--update-snapshots"]
