name: PR check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - ci-steps

jobs:
  check-semantic-pr-title:
    uses: ./.github/workflows/pr-title.yaml

  audit:
    uses: ./.github/workflows/audit.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  # build:
  #   uses: ./.github/workflows/build.yaml

  # test:
  #   uses: ./.github/workflows/test.yaml