name: PR check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  check-semantic-pr-title:
    uses: ./.github/workflows/pr-title.yml

  audit:
    uses: ./.github/workflows/audit.yml

  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  e2e-test:
    uses: ./.github/workflows/playwright.yml
    needs: build

  # test:
  #   uses: ./.github/workflows/test.yml
