name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-24.04
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      release_tag: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Generate custom token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: token
        with:
          app_id: ${{ secrets.CUSTOM_TOKEN_APP_ID }}
          private_key: ${{ secrets.CUSTOM_TOKEN_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release-please
        with:
          token: ${{ steps.token.outputs.token }}

  docker-build:
    name: Build and tag Docker image
    needs: [release-please]
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: |
        registry.aarnihalinen.fi/homepage:${{ github.sha }}
        registry.aarnihalinen.fi/homepage:next
      build-args: |
        VERSION=${{ needs.release-please.outputs.release_tag || github.sha }}
    secrets: inherit

  promote-prod:
    name: Promote to production
    needs: [release-please, docker-build]
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: registry.aarnihalinen.fi
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
          logout: true

      - name: Tag image with latest
        env:
          IMAGE: registry.aarnihalinen.fi/homepage
          SHA: ${{ github.sha }}
          RELEASE_TAG: ${{ needs.release-please.outputs.release_tag }}
        run: |
          docker pull $IMAGE:$SHA
          docker tag $IMAGE:$SHA $IMAGE:latest
          docker push $IMAGE:latest
          docker tag $IMAGE:$SHA $IMAGE:$RELEASE_TAG
          docker push $IMAGE:$RELEASE_TAG
