name: Tag staging image

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - ".release-please-manifest.json"

jobs:
  build-and-tag:
    uses: ./.github/workflows/docker-build.yml
    with:
      environment: staging
      tags: |
        registry.aarnihalinen.fi/homepage:${{ github.sha }}
        registry.aarnihalinen.fi/homepage:next
    secrets: inherit
