name: Tag staging and production image

on:
  push:
    tags:
      - v**

jobs:
  build-and-tag:
    uses: ./.github/workflows/docker-build.yml
    with:
      environment: production
      tags: |
        registry.aarnihalinen.fi/homepage:${{ github.sha }}
        registry.aarnihalinen.fi/homepage:next
        registry.aarnihalinen.fi/homepage:${{ github.ref_name }}
        registry.aarnihalinen.fi/homepage:latest
    secrets: inherit
